# @format

version: '3.5'

services:
    cache:
        container_name: uniai-redis
        privileged: true
        image: redis:latest
        restart: always
        environment:
            - REDIS_PASSWORD=${REDIS_PASS}
        command: redis-server --requirepass ${REDIS_PASS}
        ports:
            - ${REDIS_PORT}:6379
