version: '3.5'
services:
  es01:
    image: elasticsearch:8.14.3
    container_name: es01
    restart: unless-stopped
    volumes:
      - ${ES_DATA_PATH}:/usr/share/elasticsearch/data
      - ${ES_LOG_PATH}:/usr/share/elasticsearch/logs
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - 9200:9200
        # command: >
        # sh -c "yes | bin/elasticsearch-plugin install https://get.infini.cloud/elasticsearch/analysis-ik/8.14.3"

  kibana:
    image: kibana:8.14.3
    container_name: kibana
    restart: unless-stopped
    ports:
      - 5601:5601
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
    depends_on:
      - es01
