# @format

version: '3.5'

services:
    pgector:
        container_name: uniai-pgvector
        privileged: true
        image: ankane/pgvector:latest
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASS}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
