# @format

version: '3.5'

services:
    pgvector:
        container_name: pgvector
        privileged: true
        image: ankane/pgvector:latest
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
    cache:
        container_name: redis
        privileged: true
        image: redis:latest
        restart: always
        ports:
            - ${REDIS_PORT}:6379
