version: '3.5'

services:
  minio:
    container_name: uniai-minio
    privileged: true
    image: bitnami/minio:latest
    restart: always
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678
    ports:
      - '9000:9000'
      - '9001:9001'
